1st test
js-tasks-ru/htmlcss-20210114_nadezhda92 pull request #1
Opened 2021-01-14 11:24 UTC by NB1208

Initial html created, "Hello world" added.

2021-01-14 11:31 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Hello world
+ вводная задача
```
```diff
Семантическая разметка страницы
+ семантическая разметка страницы
```

Добавляю преподавателя (@Thewhiterabbit123) для код-ревью, посмотрим что он скажет :)

2021-01-14 12:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @Thewhiterabbit123

2021-01-14 19:34 UTC, Thewhiterabbit123 commented
Привет! Рада приветствовать тебя на курсе!
Мне нравится твое решение, давай только поправим несколько замечаний)

2021-01-14 19:37 UTC, Thewhiterabbit123 requested changes

2021-01-14 19:37 UTC, Thewhiterabbit123 commented on 02-dz0/01-semantic-mockup/solution.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Расскажешь для чего этот тег?

2021-01-14 19:37 UTC, Thewhiterabbit123 commented on 02-dz0/01-semantic-mockup/solution.css
> +main {
Обычно используют классы в качестве селекторов. Дело в том, что когда проект становится большим, поддерживать селекторы с тегами становится сложно.
Давай исправим на классы?
А на лекциях подробно рассмотрим методологии именования)

2021-01-18 17:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @Thewhiterabbit123

2021-01-20 13:25 UTC, PDmitryA requested changes
Привет!

Оставил один комментарий и присоединяюсь к вопросу Нади чуть выше про мета-тег.

Посмотри, пожалуйста)

2021-01-20 13:25 UTC, PDmitryA commented on 02-dz0/01-semantic-mockup/solution.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
вижу такой тег в решении у многих, а кто-то сказал, что его по-умолчанию при создании страницы добавляет vscode.
расскажи, пожалуйста, зачем он нужен? он в pull request попал осознанно?)

2021-01-20 13:25 UTC, PDmitryA commented on 02-dz0/01-semantic-mockup/solution.css
> +.nav a {
так как задание на семантическую верстку, то было бы ок стилизовать только через селекторы по тегам.
с другой стороны стилизацию сейчас принято делать на классах, поэтому селекторы по классам тоже были бы вполне ок.

смешение же оправдано только в исключительных случаях. один из них, например, когда нужно отобразить контент, сгенерированный пользователем, например, через markdown. так, на habr все авторские статьи с их заголовками, картинками, абзацами стилизованы через селекторы по тегам. `.post__text-html h3`, где `.post__text-html` - контейнер для всей статьи.

давай остановимся здесь на чем-то одном - либо классы, либо теги?

2021-01-20 15:08 UTC, NB1208 commented on 02-dz0/01-semantic-mockup/solution.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
нет, он случайно. VScode создал его. Он для мобильников, определят размер области с контентом и его масштабирование, тут конкретно не нужен..

2021-01-20 15:10 UTC, NB1208 commented
Привет,

спасибо за ответ, отписалась там.

ср, 20 янв. 2021 г. в 16:25, Dmitry Poponkin <notifications@github.com>:

> *@PDmitryA* requested changes on this pull request.
>
> Привет!
>
> Оставил один комментарий и присоединяюсь к вопросу Нади чуть выше про
> мета-тег.
>
> Посмотри, пожалуйста)
> ------------------------------
>
> In 02-dz0/01-semantic-mockup/solution.css
> <https://github.com/js-tasks-ru/htmlcss-20210114_nadezhda92/pull/1#discussion_r560953783>
> :
>
> > +.nav{
> +    background-color: orange;
> +    padding: 20px 0;
> +}
> +
> +.nav ul {
> +    margin: 0;
> +    padding: 0;
> +}
> +
> +.nav li {
> +    display: inline-block;
> +    margin: 0 30px;
> +}
> +
> +.nav a {
>
> так как задание на семантическую верстку, то было бы ок стилизовать только
> через селекторы по тегам.
> с другой стороны стилизацию сейчас принято делать на классах, поэтому
> селекторы по классам тоже были бы вполне ок.
>
> смешение же оправдано только в исключительных случаях. один из них,
> например, когда нужно отобразить контент, сгенерированный пользователем,
> например, через markdown. так, на habr все авторские статьи с их
> заголовками, картинками, абзацами стилизованы через селекторы по тегам. .post__text-html
> h3, где .post__text-html - контейнер для всей статьи.
>
> давай остановимся здесь на чем-то одном - либо классы, либо теги?
> ------------------------------
>
> In 02-dz0/01-semantic-mockup/solution.html
> <https://github.com/js-tasks-ru/htmlcss-20210114_nadezhda92/pull/1#discussion_r560948038>
> :
>
> > @@ -1,4 +1,36 @@
>  <!DOCTYPE html>
> -<html lang="ru">
> -    <!-- Ваше решение -->
> +<html lang="en">
> +<head>
> +    <meta charset="UTF-8">
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> вижу такой тег в решении у многих, а кто-то сказал, что его по-умолчанию
> при создании страницы добавляет vscode.
> расскажи, пожалуйста, зачем он нужен? он в pull request попал осознанно?)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/htmlcss-20210114_nadezhda92/pull/1#pullrequestreview-572203664>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQPDM4KVSABKAEB3QWA5VS3S23KVTANCNFSM4WCI65FA>
> .
>

2021-01-21 08:35 UTC, PDmitryA commented on 02-dz0/01-semantic-mockup/solution.css
> +.nav a {
поправишь в этом месте?

2021-01-21 14:36 UTC, NB1208 commented on 02-dz0/01-semantic-mockup/solution.css
> +.nav a {
а как же .nav ul  и .nav li ?
с учётом того что мы не знаем будет ли данный файл масштабироваться - есть ли смысл прописывать тут классы.

2021-01-21 15:55 UTC, diarmind commented on 02-dz0/01-semantic-mockup/solution.css
> +.nav a {
`.nav ul` и `.nal li` тоже
файл масштабироваться не будет - это лишь задача. но если бы это был реальный проект, то нужно было бы исправить. поэтому и в задаче прошу поправить

2021-01-21 16:15 UTC, NB1208 commented on 02-dz0/01-semantic-mockup/solution.css
> +.nav a {
спасибо. запушила откорректированную версию.

2021-01-21 16:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @Thewhiterabbit123

2021-01-21 17:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @Thewhiterabbit123

2021-01-21 20:57 UTC, PDmitryA reviewed
нулевое дз - ок!

2021-01-21 21:10 UTC, PDmitryA requested changes
так как в `master` появилась еще задача с `button`, то принять можем только все вместе. нулевое дз принято)

По кнопке:
1. для `alternative` стиль для состояния `:disabled` нужно описать.
2. курсор для `:disabled` на всех кнопках нужно из состояния `pointer` перевести в `default` или `not-allowed`.

2021-01-21 21:10 UTC, PDmitryA commented on 03-lection1/01-button/button.css
> +.btn--primary {
хмм, модификатор от блока в данном случае отделен через `--`? а как блок от элемента отделяется?

либо в твоем проекте будет какая-то специфичная система именования (что в целом допустимо, просто скажи, какая), либо название класса не по БЭМу. ниже тоже такая проблема.

2021-01-21 21:10 UTC, PDmitryA commented on 03-lection1/01-button/index.html
> +        <div class="btn-group">
класс присвоен, но стилей к нему нет. можно убрать тогда.

2021-01-22 09:15 UTC, NB1208 commented on 03-lection1/01-button/button.css
> +.btn--primary {
использовала стиль Two Dashes https://ru.bem.info/methodology/naming-convention/
блок от элемента двумя нижними подчёркиваниями был бы.

2021-01-22 09:35 UTC, PDmitryA commented on 03-lection1/01-button/button.css
> +.btn--primary {
окей

2021-01-22 13:28 UTC, NB1208 commented on 03-lection1/01-button/index.html
> +        <div class="btn-group">
убрала

2021-01-22 13:29 UTC, NB1208 commented on 03-lection1/01-button/button.css
> +.btn--primary {
поправила disabled для .alternative и установила курсору not-allowed.

2021-01-22 14:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @Thewhiterabbit123

2021-01-23 09:13 UTC, PDmitryA approved these changes
все отлично, мержим!

2021-01-23 09:14 UTC, merged