scss and some fixes
js-tasks-ru/htmlcss-20210114_nadezhda92 pull request #3
Opened 2021-02-24 17:02 UTC by NB1208

2021-02-24 17:02 UTC, jsru commented
Добавляю преподавателя (@PDmitryA) для код-ревью.

2021-02-24 23:16 UTC, PDmitryA requested changes
небольшая путаница с тем, что и куда собирается. расскажи идею `lib`, пожалуйста. можно в слаке.

2021-02-24 23:16 UTC, PDmitryA commented on postcss.config.js
> +        // require('precss')({
ну, я закоментированный код в примере показывал)
для чистовика, конечно, нужно удалить.

p.s.
в целом хорошая практика не держать закомментированного кода в репозитории.
он мертв и не воскреснет. никогда.
проще написать новый будет, когда понадобится)

2021-02-24 23:16 UTC, PDmitryA commented on package.json
> +    "build-lib": "postcss assets/css/lib.scss -o build/lib-index.css",
вижу, что поняла, очень круто, молодец!

2021-02-24 23:16 UTC, PDmitryA commented on assets/css/main.scss
> +@import '../../07-lection5/04-input/input.scss';
не понял, почему инпут тут. он такой же, как и все компоненты

2021-02-24 23:16 UTC, PDmitryA commented on assets/css/lib.scss
> +@import "./main.css";
совсем запутался. итого - есть один бандл `lib`, в который попадает все.
а зачем команда сборки `main.scss` в `package.json`? если и правда не нужна, то давай ее заменим на твою :)

конкретно к этой строчке - main.css => main.scss
+ строчкой выше импортируешь normalize.css. он уже есть в main.scss. можно не импортировать.

2021-02-25 21:48 UTC, PDmitryA approved these changes

2021-02-25 21:48 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2021-02-25 21:48 UTC, merged